import CoreData
import Foundation
import SwiftUI

// The managed object classes themselves are generated by Xcode from
// DosiCrew.xcdatamodeld (codeGenerationType = class). Everything below adds the
// type-safe layer on top of the `@NSManaged` properties, plus the conversion
// into the plain snapshots `ScheduleEngine` works with.

// MARK: - Patient

extension Patient {
    var displayName: String {
        let trimmed = (name ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? String(localized: "Unnamed") : trimmed
    }

    /// The colour this child's name is written in.
    ///
    /// Stored on the record, so every iPhone sharing the plan shows the same
    /// one. Falls back to a colour derived from the identifier for records
    /// created before colours were assigned — anything but letting them all
    /// come out the same.
    var displayColor: Color {
        if let hex = colorHex, let stored = Color(hex: hex) { return stored }
        guard let id else { return ChildColor.fallback.color }
        return ChildColor.derived(from: id).color
    }

    var sortedMedications: [Medication] {
        let all = (medications as? Set<Medication>) ?? []
        return all.sorted { lhs, rhs in
            if lhs.isArchived != rhs.isArchived { return !lhs.isArchived }
            if lhs.sortOrder != rhs.sortOrder { return lhs.sortOrder < rhs.sortOrder }
            return lhs.displayName.localizedStandardCompare(rhs.displayName) == .orderedAscending
        }
    }

    var activeMedications: [Medication] { sortedMedications.filter { !$0.isArchived } }

    var sortedEvents: [CareEvent] {
        let all = (events as? Set<CareEvent>) ?? []
        return all.sorted { ($0.timestamp ?? .distantPast) > ($1.timestamp ?? .distantPast) }
    }

    @discardableResult
    static func makeDefault(in context: NSManagedObjectContext) -> Patient {
        let patient = Patient(context: context)
        patient.id = UUID()
        patient.name = String(localized: "My child")
        // Picked against the siblings that already exist, so no two children
        // in one plan share a colour.
        patient.colorHex = ChildColor.unused(among: existingColorHexes(in: context)).rawValue
        patient.createdAt = Date()
        return patient
    }

    private static func existingColorHexes(in context: NSManagedObjectContext) -> [String?] {
        let request = NSFetchRequest<Patient>(entityName: "Patient")
        return ((try? context.fetch(request)) ?? []).map(\.colorHex)
    }

    /// The oldest patient, creating one if the app has never been used.
    ///
    /// Several children are supported — each is its own share root, so one can
    /// be shared with the childminder and another only with a grandparent. This
    /// helper exists for first launch and for previews, not as "the" patient.
    static func fetchOrCreate(in context: NSManagedObjectContext) -> Patient {
        let request = NSFetchRequest<Patient>(entityName: "Patient")
        request.sortDescriptors = [NSSortDescriptor(key: "createdAt", ascending: true)]
        request.fetchLimit = 1
        if let existing = (try? context.fetch(request))?.first { return existing }
        return makeDefault(in: context)
    }
}

// MARK: - Medication

extension Medication {
    var displayName: String {
        let trimmed = (name ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? String(localized: "Unnamed medication") : trimmed
    }

    var formEnum: MedicationForm {
        get { MedicationForm(rawValue: form) ?? .other }
        set { form = newValue.rawValue }
    }

    var color: Color { Color(hex: colorHex ?? "") ?? MedColor.fallback.color }

    var sortedRules: [ScheduleRule] {
        let all = (rules as? Set<ScheduleRule>) ?? []
        return all.sorted { ($0.firstMinute ?? Int.max) < ($1.firstMinute ?? Int.max) }
    }

    var allLogs: [DoseLog] {
        let all = (logs as? Set<DoseLog>) ?? []
        return all.sorted { ($0.takenAt ?? .distantPast) > ($1.takenAt ?? .distantPast) }
    }

    /// "5 ml" — the amount handed over at one slot. Empty when nothing is set,
    /// so callers can hide the label rather than print a bare "0".
    var doseDescription: String {
        Medication.doseDescription(amount: doseAmount, unit: doseUnit ?? "")
    }

    static func doseDescription(amount: Double, unit rawUnit: String) -> String {
        let unit = rawUnit.trimmingCharacters(in: .whitespaces)
        guard amount > 0 else { return unit.isEmpty ? "" : DoseUnit.localizedName(for: unit) }
        let formatted = doseFormatter.string(from: NSNumber(value: amount)) ?? "\(amount)"
        return unit.isEmpty ? formatted : "\(formatted) \(DoseUnit.localizedName(for: unit))"
    }

    static let doseFormatter: NumberFormatter = {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.minimumFractionDigits = 0
        formatter.maximumFractionDigits = 3
        return formatter
    }()

    @discardableResult
    static func make(in context: NSManagedObjectContext, patient: Patient) -> Medication {
        let medication = Medication(context: context)
        medication.id = UUID()
        medication.createdAt = Date()
        medication.colorHex = MedColor.fallback.rawValue
        medication.formEnum = .tablet
        medication.doseUnit = MedicationForm.tablet.defaultUnit
        medication.isArchived = false
        medication.patient = patient
        medication.sortOrder = Int16(clamping: patient.sortedMedications.count)
        return medication
    }

    func snapshot() -> MedicationSnapshot {
        MedicationSnapshot(
            id: id ?? UUID(),
            name: displayName,
            patientID: patient?.id ?? UUID(),
            patientName: patient?.displayName ?? "",
            patientColorHex: patient?.colorHex ?? ChildColor.fallback.rawValue,
            doseAmount: doseAmount,
            doseUnit: (doseUnit ?? "").trimmingCharacters(in: .whitespaces),
            form: formEnum,
            colorHex: colorHex ?? MedColor.fallback.rawValue,
            instructions: instructions,
            startDate: startDate,
            endDate: endDate,
            isArchived: isArchived,
            rules: sortedRules.map { $0.snapshot() }
        )
    }
}

// MARK: - ScheduleRule

extension ScheduleRule {
    var minutes: [Int] {
        get { ScheduleEngine.parseMinutes(minutesOfDay) }
        set { minutesOfDay = ScheduleEngine.encodeMinutes(newValue) }
    }

    var firstMinute: Int? { minutes.first }

    var recurrenceEnum: Recurrence {
        get { Recurrence(rawValue: recurrence) ?? .daily }
        set { recurrence = newValue.rawValue }
    }

    var weekdaySet: Set<Int> {
        get { ScheduleEngine.weekdays(in: Int(weekdayMask)) }
        set { weekdayMask = Int16(clamping: ScheduleEngine.weekdayMask(for: newValue)) }
    }

    @discardableResult
    static func make(in context: NSManagedObjectContext, medication: Medication) -> ScheduleRule {
        let rule = ScheduleRule(context: context)
        rule.id = UUID()
        rule.recurrenceEnum = .daily
        rule.intervalDays = 1
        rule.weekdayMask = Int16(ScheduleEngine.allWeekdaysMask)
        // No times. A guessed 08:00 is not a head start — it has to be deleted
        // after the real time is added, and deleting the one entry that is
        // already there is more work than adding the one that is wanted.
        rule.minutes = []
        rule.medication = medication
        return rule
    }

    func snapshot() -> ScheduleRuleSnapshot {
        ScheduleRuleSnapshot(
            minutesOfDay: minutes,
            recurrence: recurrenceEnum,
            intervalDays: Int(intervalDays),
            weekdayMask: Int(weekdayMask),
            startDate: startDate,
            endDate: endDate
        )
    }
}

// MARK: - DoseLog

extension DoseLog {
    var statusEnum: DoseStatus {
        get { DoseStatus(rawValue: status) ?? .given }
        set { status = newValue.rawValue }
    }

    func snapshot() -> DoseLogSnapshot? {
        guard let medicationID = medication?.id else { return nil }
        return DoseLogSnapshot(
            id: id ?? UUID(),
            medicationID: medicationID,
            scheduledAt: scheduledAt,
            takenAt: takenAt,
            status: statusEnum,
            amountGiven: amountGiven,
            personName: personName,
            note: note
        )
    }

    @discardableResult
    static func make(
        in context: NSManagedObjectContext,
        medication: Medication,
        scheduledAt: Date?,
        status: DoseStatus,
        personName: String,
        takenAt: Date = Date()
    ) -> DoseLog {
        let log = DoseLog(context: context)
        log.id = UUID()
        log.medication = medication
        log.scheduledAt = scheduledAt
        log.takenAt = takenAt
        log.statusEnum = status
        log.amountGiven = medication.doseAmount
        log.personName = personName
        log.personRecordName = nil
        return log
    }
}

// MARK: - CareEvent

extension CareEvent {
    var categoryEnum: EventCategory {
        get { EventCategory(rawValue: category) ?? .note }
        set { category = newValue.rawValue }
    }

    var displayTitle: String {
        let trimmed = (title ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? String(localized: "Event") : trimmed
    }

    /// "38.9 °C", "120/80 mmHg", "110 mg/dl (6.1 mmol/l)" — or nil when the
    /// event carries no measurement.
    ///
    /// Blood sugar shows both units because a shared plan is exactly where two
    /// people read two different ones, and a number without the unit they think
    /// in is a number they have to convert in their head.
    var measurementDescription: String? {
        // A seizure whose duration nobody caught still carries its kind, and
        // that is the half a neurologist would rather have.
        if categoryEnum == .seizure, !hasMeasurement {
            return SeizureType.from(code: detailCode)?.label
        }
        guard hasMeasurement else { return nil }

        switch categoryEnum.measurementShape {
        case .bloodPressure:
            return BloodPressure.description(
                systolic: measurementValue,
                diastolic: measurementSecondaryValue
            ) + " " + BloodPressure.unit

        case .bloodSugar:
            let unit = BloodSugarUnit.from(unitString: measurementUnit) ?? .mgPerDeciliter
            return unit.descriptionWithConversion(measurementValue)

        case .seizure:
            // The kind first: for a neurologist reading the diary, "atypical
            // absence" is the fact and the duration qualifies it.
            let kind = SeizureType.from(code: detailCode)?.label
            let duration = measurementValue > 0
                ? SeizureDuration.description(seconds: measurementValue)
                : nil
            return [kind, duration].compactMap { $0 }.joined(separator: " · ").nilIfEmpty

        case .single, .noValue:
            let value = Medication.doseFormatter.string(from: NSNumber(value: measurementValue))
                ?? "\(measurementValue)"
            let unit = (measurementUnit ?? "").trimmingCharacters(in: .whitespaces)
            return unit.isEmpty ? value : "\(value) \(unit)"
        }
    }

    @discardableResult
    static func make(in context: NSManagedObjectContext, patient: Patient) -> CareEvent {
        let event = CareEvent(context: context)
        event.id = UUID()
        event.timestamp = Date()
        event.categoryEnum = .fever
        event.measurementUnit = EventCategory.fever.suggestedUnit
        event.patient = patient
        return event
    }
}
