#!/usr/bin/env bash
#
# Creates the CloudKit development schema — the one step that needs a Mac.
#
# Background: TestFlight and App Store builds always talk to CloudKit's
# *production* environment, and the schema has to be there before the first
# such build. The schema itself is only ever generated by a run in the
# *development* environment. That run needs Xcode and an iCloud account, so it
# cannot happen in CI or on a Linux machine.
#
# This script does the mechanical part — build, install, launch with the right
# argument — so the only manual steps left are the two that genuinely need a
# human: signing into iCloud in the Simulator, and pressing "Deploy" in the
# CloudKit Console. On a rented Mac over a remote desktop, that matters.
#
# Usage:
#   ./Tools/bootstrap-cloudkit.sh <APPLE_TEAM_ID>
#
set -euo pipefail

BUNDLE_ID="es.reichenbach.DosiCrew"
CONTAINER="iCloud.es.reichenbach.DosiCrew"
SCHEME="DosiCrew"
PROJECT="DosiCrew.xcodeproj"
DERIVED="build/bootstrap"

die() { printf '\n\033[31mAbbruch:\033[0m %s\n\n' "$1" >&2; exit 1; }
step() { printf '\n\033[1m▸ %s\033[0m\n' "$1"; }

[ -d "$PROJECT" ] || die "Bitte im Wurzelverzeichnis des Repos ausführen (dort liegt $PROJECT)."

TEAM="${1:-${APPLE_TEAM_ID:-}}"
[ -n "$TEAM" ] || die "Team-ID fehlt. Aufruf: ./Tools/bootstrap-cloudkit.sh <APPLE_TEAM_ID>
Die zehnstellige ID steht oben rechts auf developer.apple.com."

step "Xcode prüfen"
command -v xcodebuild >/dev/null || die "xcodebuild nicht gefunden. Xcode installieren und einmal öffnen."
XCODE_VERSION=$(xcodebuild -version | head -1 | awk '{print $2}')
XCODE_MAJOR=${XCODE_VERSION%%.*}
echo "Xcode $XCODE_VERSION"
[ "$XCODE_MAJOR" -ge 16 ] || die "Xcode 16 oder neuer nötig — das Projekt nutzt das Ordnerformat von Xcode 16.
Gefunden: $XCODE_VERSION"

step "Simulator wählen"
UDID=$(xcrun simctl list devices available --json | python3 .github/scripts/pick_simulator.py)
xcrun simctl boot "$UDID" 2>/dev/null || true
open -a Simulator
echo "Simulator $UDID gestartet."

cat <<EOF

┌────────────────────────────────────────────────────────────────────┐
│  JETZT IM SIMULATOR IN ICLOUD ANMELDEN                             │
│                                                                    │
│  Einstellungen → Beim iPhone anmelden → deine Apple-ID.            │
│  Ohne angemeldetes Konto kann CloudKit nichts anlegen.             │
└────────────────────────────────────────────────────────────────────┘

EOF
read -r -p "Angemeldet? Dann Enter drücken. " _

step "App bauen (Debug, für den Simulator)"
# Mit Signierung: die iCloud-Entitlements müssen ins Bundle, sonst redet die
# App nicht mit CloudKit. Simulator-Builds brauchen dafür kein
# Provisioning-Profil und kein registriertes Gerät.
xcodebuild build \
  -project "$PROJECT" \
  -scheme "$SCHEME" \
  -configuration Debug \
  -destination "platform=iOS Simulator,id=$UDID" \
  -derivedDataPath "$DERIVED" \
  DEVELOPMENT_TEAM="$TEAM" \
  | tail -20

APP="$DERIVED/Build/Products/Debug-iphonesimulator/$SCHEME.app"
[ -d "$APP" ] || die "Gebautes App-Bundle nicht gefunden unter $APP"

step "Installieren und mit dem Bootstrap-Argument starten"
xcrun simctl install "$UDID" "$APP"
echo "Der Start dauert jetzt spürbar länger — das Anlegen des Schemas blockiert."
echo

# --console-pty leitet die Ausgabe der App hierher, damit der umrahmte
# Erfolgsblock direkt im Terminal steht statt im Unified Log.
xcrun simctl launch --console-pty "$UDID" "$BUNDLE_ID" -DosiCrewInitializeCloudKitSchema || true

cat <<EOF

┌────────────────────────────────────────────────────────────────────┐
│  LETZTER SCHRITT — im Browser                                      │
│                                                                    │
│  icloud.developer.apple.com → CloudKit Console                     │
│  Container: $CONTAINER
│  → Schema → Deploy Schema Changes → Production                     │
│                                                                    │
│  Danach synchronisiert der bereits installierte TestFlight-Build   │
│  von selbst. Ein neuer Upload ist nicht nötig.                     │
└────────────────────────────────────────────────────────────────────┘

EOF
